st1 [1994][ADD] stock_picking_type_kanban_view
qrtl/rpl-custom pull request #164
Opened 2021-11-12 10:55 UTC by kakurai8

[1994](https://www.quartile.co/web#id=1994&model=project.task&view_type=form&menu_id=)

やりたいこと
- 「アクションの編集」に{"search_default_groupby_warehouse_id": 1}を追加する。だけ

できていない
- 元の検索ビューからinheritする必要があると思われる

2021-11-26 13:08 UTC, tack-yabeQuartile commented
For now, this module is not recognized as a part of Stock module, so a new app is displayed after installing.

2021-11-26 13:12 UTC, yostashiro commented
@kakurai8 @tack-yabeQuartile Should have advised earlier, but can you update this module https://github.com/qrtl/rpl-private/tree/12.0/stock_view_adj_rpl instead of adding a new one, since this change doesn't carry such a strong business context. It's a bit of an overkill to create a dedicated module.

2021-11-26 13:37 UTC, yostashiro requested changes

2021-11-26 13:37 UTC, yostashiro commented on stock_picking_type_kanban_view/views/stock_picking_type_kanban_view.xml
> +    />
```suggestion
```
This shouldn't be needed.

2021-11-26 13:37 UTC, yostashiro commented on stock_picking_type_kanban_view/views/stock_picking_type_kanban_view.xml
> +    </record>
```suggestion
    <record id="stock.stock_picking_type_action" model="ir.actions.act_window">
        <field name="context">{"search_default_groupby_warehouse_id": 1}</field>
    </record>
```

2021-11-29 01:40 UTC, tack-yabeQuartile commented
> can you update stock_view_adj_rpl instead of adding a new one
OK, I see the code after change and I feel the change is too small  to create a new custom module.

2021-11-29 01:57 UTC, tack-yabeQuartile commented
moved to https://github.com/qrtl/rpl-private/pull/220

2021-11-29 01:57 UTC, closed without merging