st1 [2034][ADD] stock_picking_partner_info
qrtl/rpl-custom pull request #170
Opened 2021-12-03 10:13 UTC by tack-yabeQuartile

[#2034](https://www.quartile.co/web#id=2034&model=project.task&view_type=form&menu_id=)

* Display address and phone at delivery form.

This PR supersedes rpl-private #223.

2021-12-03 10:23 UTC, tack-yabeQuartile commented
Commands below was used to make this PR.
```
cd rpl-custom
git checkout st1
git pull --ff-only origin st1
git checkout -b 2034_ADD_stock_picking_partner_info
git remote add custom https://github.com/qrtl/rpl-private
git fetch custom
git format-patch --keep-subject --stdout origin/st1..custom/2014_2034_imp_stock_view_adj_rpl -- stock_picking_partner_info | git am -3 --keep
git push origin HEAD
```

2021-12-06 03:19 UTC, TomohiroAbe-Quartile approved these changes
Code side: LGTM

2021-12-06 04:10 UTC, yostashiro requested changes

2021-12-06 04:10 UTC, yostashiro commented on stock_picking_partner_info/views/stock_picking_views.xml
> +                <attribute name="options">{'always_reload': 1}</attribute>
```suggestion
                <attribute name="options">{'always_reload': 1}</attribute>
                <attribute name="attrs">{'invisible': [('picking_type_code', '!=', 'outgoing')]}</attribute>
```

2021-12-06 04:10 UTC, yostashiro commented on stock_picking_partner_info/views/stock_picking_views.xml
> +                <field name="phone" widget="phone" />
```suggestion
                <field name="phone" widget="phone" attrs="{'invisible': [('picking_type_code', '!=', 'outgoing')]}"/>
```

2021-12-06 04:10 UTC, yostashiro commented on stock_picking_partner_info/models/stock_picking.py
> +# Copyright 2021 Quartile Limited
```suggestion
# Copyright 2021 Quartile Limited
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```

2021-12-06 04:10 UTC, yostashiro commented on stock_picking_partner_info/readme/DESCRIPTION.rst
> +* Display address in partner field and add phone field to the transfer order form.
```suggestion
* Displays the partner address and phone in the transfer form for outgoing deliveries.
```

2021-12-06 04:10 UTC, yostashiro commented on stock_picking_partner_info/__manifest__.py
> +    "depends": [],
```suggestion
```

2021-12-06 06:47 UTC, tack-yabeQuartile commented
temporary changed to DRAFT.
An error happened when installing/updateing this module.

2021-12-06 10:15 UTC, yostashiro approved these changes

2021-12-07 03:40 UTC, merged