12.0  [2034][ADD] stock_picking_partner_info
qrtl/rpl-custom pull request #174
Opened 2021-12-15 10:08 UTC by tack-yabeQuartile

[#2034](https://www.quartile.co/web#view_type=form&model=project.task&id=2034&active_id=2034&menu_id=)

st1
#170 #173

2021-12-16 02:04 UTC, yostashiro requested changes

2021-12-16 02:04 UTC, yostashiro commented on stock_picking_partner_info/views/stock_picking_views.xml
> +            </xpath>
```suggestion
            <xpath expr="//field[@name='partner_id']" position="attributes">
                <attribute name="context">{'show_address': 1}</attribute>
                <attribute name="options">{'always_reload': 1}</attribute>
                <attribute
                    name="attrs"
                >{'invisible': [('picking_type_code', '!=', 'outgoing')]}</attribute>
            </xpath>
            <xpath expr="//field[@name='partner_id']" position="after">
                <field name="partner_id" attrs="{'invisible': [('picking_type_code', '=', 'outgoing')]}" />
            </xpath>
```
There was an oversight by me that the partner field was not showing for receipts, so we should either remove the invisible attribute or add another partner_id field to show in when the picking type code is not outgoing.

2021-12-16 02:20 UTC, tack-yabeQuartile commented
We wait one more staging PR to fix layout of receipt.

2021-12-17 04:56 UTC, yostashiro approved these changes
👍

2021-12-17 04:59 UTC, merged